"""Shared data constants for pytoolbox."""

# pylint: disable=line-too-long

sentences = (
    "The longest time between two twins being born is 87 days.",
    "The world’s deepest postbox is in Susami Bay in Japan. It’s 10 meters underwater.",
    "In 2007, an American man named Corey Taylor tried to fake his own death in order to get out of his cell phone contract without paying a fee. It didn’t work.",
    "The oldest condoms ever found date back to the 1640s. They were made from animal and fish intestines.",
    "In 1923, a jockey suffered a fatal heart attack but his horse finished and won the race, making him the first and only jockey to win a race after death.",
    "Be the change that you wish to see in the world. ― Mahatma Gandhi",
    "Don’t judge each day by the harvest you reap but by the seeds that you plant. ― Robert Louis Stevenson",
    "The only person you are destined to become is the person you decide to be. ― Ralph Waldo Emerson",
    "Start where you are. Use what you have. Do what you can. ― Arthur Ashe",
    "Everything you’ve ever wanted is on the other side of fear. ― George Addair",
    "In 2006, a Coca-Cola employee offered to sell Coca-Cola secrets to Pepsi. Pepsi responded by notifying Coca-Cola.",
    "There’s only one letter that doesn’t appear in any U.S. state name: Q.",
    "A sheep, a duck and a rooster were the first passengers in a hot air balloon.",
    "In Uganda, around 48% of the population is under 15 years of age.",
    "The average male gets bored of a shopping trip after 26 minutes.",
    "If you want to live a happy life, tie it to a goal, not to people or things. ― Albert Einstein",
    "Success is not final, failure is not fatal: it is the courage to continue that counts. ― Winston S. Churchill",
    "The journey of a thousand miles begins with a single step. ― Lao Tzu",
    "The most common way people give up their power is by thinking they don’t have any. ― Alice Walker",
    "The most difficult thing is the decision to act, the rest is merely tenacity. ― Amelia Earhart",
    "There are more stars in space than there are grains of sand on every beach in the world.",
    "For every human on Earth there are 1.6 million ants.",
    "The total weight of all those ants, however, is about the same as all the humans.",
    "On Jupiter and Saturn it rains diamonds.",
    "Ten percent of all the photos ever taken were taken in the last 12 months.",
    "Believe you can and you’re halfway there. ― Theodore Roosevelt",
    "When one door of happiness closes, another opens; but often we look so long at the closed door that we do not see the one which has been opened for us. ― Helen Keller",
    "You must be the change you wish to see in the world. ― Mahatma Gandhi",
    "The mind is everything. What you think you become.  ― Buddha",
    "The question isn’t who is going to let me; it’s who is going to stop me. ― Ayn Rand",
    "Scotland has 421 words for “snow”.",
    "Samsung tests phone durability with a butt-shaped robot.",
    "The Twitter bird actually has a name – Larry.",
    "Octopuses have three hearts.",
    "If you lift a kangaroo’s tail off the ground it can’t hop – they use their tails for balance.",
    "Whatever you can do, or dream you can, begin it. Boldness has genius, power and magic in it. ― Johann Wolfgang von Goethe",
    "I’ve learned that people will forget what you said, people will forget what you did, but people will never forget how you made them feel. ― Maya Angelou",
    "Whether you think you can or you think you can’t, you’re right. ― Henry Ford",
    "Perfection is not attainable, but if we chase perfection we can catch excellence. ― Vince Lombardi",
)

PATTERNS = {
    '<UUID4>': '(?P<UUID4>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})',
    '<DOMAIN_PORT>': '(?P<DOMAIN_PORT>([a-z0-9]+(-[a-z0-9]+)*\\.)*([a-z0-9]+(-[a-z0-9]+)*\\.)+[a-z]{2,}:\\d{1,5})',
}
